# Generated by Django 5.0.7 on 2024-11-04 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='created_by',
            field=models.ForeignKey(help_text='The user who created this notification.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_notification_created_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
