# Generated by Django 5.0.3 on 2024-04-20 20:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique identifier for this notification.', unique=True)),
                ('is_enable_notification', models.BooleanField(default=True, verbose_name='Enable Notifications')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp indicating when the notification settings was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp indicating when the notification settings was last updated.')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Notification Setting',
                'verbose_name_plural': 'Notification Settings',
            },
        ),
    ]
