# Generated by Django 5.0.4 on 2024-04-28 07:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notificationsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp indicating when the instance was created.'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='uid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique identifier for this model instance.', unique=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp indicating when the instance was last updated.'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp indicating when the instance was created.'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='uid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique identifier for this model instance.', unique=True),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp indicating when the instance was last updated.'),
        ),
    ]
